---


# Install Legion core chart
- name: Get jenkins volume info
  ec2_vol:
    state: list
    region: "{{ aws_region }}"
    name: "jenkins_home_{{ profile }}"
    zone: "{{ cluster_zones.0.zone_name }}"
    tags:
      App: "jenkins_home_{{ cluster_name }}"
  register: ec2_jenkins_vol
  tags: jenkins_volume
  when: persistent_jenkins_volume