rootDomain: k8s-nightly.epm.kharlamov.biz
localDomain: "cluster.local"
enclaveDeploymentPrefix: "legion-"
domainDelimiter: "."
cluster_prefix: ""

auth:
  enabled: false
  annotations: {}

metrics:
  enabled: true
  host: statsd-exporter.kube-monitoring.svc.cluster.local
  port: 9125

jenkins:
  enabled: true
  image:
    repository: "legion/k8s-jenkins"
    tag: "latest"

  rbac: true

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: jenkins
    tls:
      enabled: true
      autoSecretNameDeduction: true

  git_secret_name: false

  persistence:
    storageClass: ""
    size: 20Gi

  openId:
    enable: false
    clientId: ~
    clientSecret: ~
    tokenServerUrl: ~
    authServerUrl: ~
    adminGroups: ~
    readOnlyGroups: ~

connections:
  docker:
    type: proxy
    url: ~
    user: ~
    password: ~
